# Generated by Django 3.2.21 on 2023-11-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MayaElectronics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department_name',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('F', 'Finance'), ('M', 'Mantainence'), ('P', 'Production')], max_length=255),
        ),
    ]
